---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact:
    ansible_distribution: centos
  when: ansible_distribution == "RedHat"

- name: copy file hids-ossec
  copy:
    src: "files/ossec-hids-{{ ossec_server_release_version }}.rpm"
    dest: "/tmp/ossec-hids.rpm"

- name: copy file hids-ossec-server
  copy:
    src: files/ossec-hids-server-{{ ossec_server_release_version }}.rpm
    dest: /tmp/ossec-hids-server.rpm

- name: install hids-ossec
  yum:
    name: /tmp/ossec-hids.rpm
    state: present

- name: install hids-ossec-server
  yum:
    name: /tmp/ossec-hids-server.rpm
    state: present

- name: "Set ossec deploy facts for RedHat"
  set_fact:
    ossec_server_config_filename: ossec-server.conf
    ossec_init_name: ossec-hids
